// integrations/react/Badge.tsx
import React from 'react';
import 'quantumcss/dist/components/badge.css';

interface BadgeProps {
  variant?: 'primary' | 'success' | 'warning' | 'danger';
  dot?: boolean;
  children?: React.ReactNode;
}

export const Badge: React.FC<BadgeProps> = ({ variant = 'primary', dot, children }) => {
  const classes = [
    'q-badge',
    `q-badge-${variant}`,
    dot && 'q-badge-dot'
  ].filter(Boolean).join(' ');

  return <span className={classes}>{children}</span>;
};

// integrations/vue/Badge.vue
<script setup lang="ts">
/**
 * QuantumCSS Badge for Vue 3
 */
withDefaults(defineProps<{
  variant?: 'primary' | 'success' | 'warning' | 'danger';
}>(), {
  variant: 'primary'
});
</script>

<template>
  <span class="q-badge" :class="`q-badge-${variant}`">
    <slot />
  </span>
</template>

<style scoped>
@import 'quantumcss/dist/components/badge.css';
</style>
