// integrations/vue/Button.vue
<script setup lang="ts">
/**
 * QuantumCSS Button for Vue 3
 */
defineProps<{
  primary?: boolean;
  disabled?: boolean;
  small?: boolean;
}>();
</script>

<template>
  <button
    class="q-btn"
    :class="{ 'q-btn-primary': primary, 'q-btn-small': small }"
    :disabled="disabled"
  >
    <slot />
  </button>
</template>

<style scoped>
@import 'quantumcss/dist/components/button.css';
</style>

// integrations/react/Button.tsx
import React from 'react';
import 'quantumcss/dist/components/button.css';

interface ButtonProps {
  primary?: boolean;
  disabled?: boolean;
  loading?: boolean;
  children: React.ReactNode;
  onClick?: () => void;
}

export const Button: React.FC<ButtonProps> = ({
  primary,
  disabled,
  loading,
  children,
  onClick
}) => {
  const classes = [
    'q-btn',
    primary && 'q-btn-primary',
    loading && 'q-btn-loading'
  ].filter(Boolean).join(' ');

  return (
    <button 
      className={classes}
      disabled={disabled || loading}
      onClick={onClick}
    >
      {children}
    </button>
  );
};
