// src/components/vue/Button.vue
<template>
  <button
    :class="classes"
    :disabled="disabled || loading"
    @click="$emit('click', $event)"
  >
    <slot />
  </button>
</template>

<script>
export default {
  name: 'QButton',
  props: {
    primary: Boolean,
    secondary: Boolean,
    disabled: Boolean,
    loading: Boolean
  },
  computed: {
    classes() {
      return {
        'q-btn': true,
        'q-btn-primary': this.primary,
        'q-btn-secondary': this.secondary,
        'q-btn-loading': this.loading
      };
    }
  }
}
</script>

// integrations/react/Button.tsx
import React from 'react';
import 'quantumcss/dist/components/button.css';

interface ButtonProps {
  primary?: boolean;
  disabled?: boolean;
  loading?: boolean;
  children: React.ReactNode;
  onClick?: () => void;
}

export const Button: React.FC<ButtonProps> = ({
  primary,
  disabled,
  loading,
  children,
  onClick
}) => {
  const classes = [
    'q-btn',
    primary && 'q-btn-primary',
    loading && 'q-btn-loading'
  ].filter(Boolean).join(' ');

  return (
    <button 
      className={classes}
      disabled={disabled || loading}
      onClick={onClick}
    >
      {children}
    </button>
  );
};
